version: "3.9"
services:
  app:
    build:
      context: ../app
    image: ghcr.io/youruser/portfolio-demo:latest
    container_name: demo-app
    ports: ["8080:8080"]
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: demo-prom
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: demo-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports: ["3000:3000"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: demo-cadvisor
    privileged: true
    ports: ["8081:8080"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
