name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build
        run: |
          docker build -t ghcr.io/${{ github.repository }}/portfolio-demo:${{ github.sha }} ./app
          docker tag ghcr.io/${{ github.repository }}/portfolio-demo:${{ github.sha }} ghcr.io/${{ github.repository }}/portfolio-demo:latest
      - name: Push
        run: |
          docker push ghcr.io/${{ github.repository }}/portfolio-demo:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/portfolio-demo:latest
